apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
spec:
  rules:
  - host: myapp.com # This is the host that user will enter its browser
    http:
      paths:
      - backend: # http://myapp.com/...
          serviceName: myapp-internal-service
          servicePort: 8080
---
apiVersion: v1
kind: Service #Internal service. There is no nodePort in internal service.
metadata:
  name: myapp-internal-service # must match the serviceName in Ingress
spec:
  selector:
    app: myapp
  ports: 
  - protocol: TCP
    port: 8080 # must match servicePort in Ingress
    targetPort: 8080
