apiVersion: v1
kind: PersistantVolume
metadata:
  name: pv-name
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessMode: 
    - ReadWriteOnce
  persistantVolumeReclaimPolicy: Recycle
  storageClassName: slow
  mountOptions:
    - hard
    - nfsvers=4.0
  nfs:
    path: /dir/path/pm/nfs/server
    server: nfs-server-ip-address
